### ISSUE TITLE
<Cast: Spell> text should be easier to read and not block combat text

### ISSUE THREAD

**Issue by griever989** [griever989/endless-expedition#11]
We should show spell casts, interrupts, status affliction application, etc in a different way than jamming it on top of the damage text. Maybe we can show it moving upwards from the middle of the character or farther above their head; just some way to make it not block the damage numbers.

**Comment by sigseg1v** [comment]
Fixed with the phaser3 migration where I changed the direction that status messages scroll in the combat text.
