### ISSUE TITLE
HTTPS certificate should hot reload when updated

### ISSUE THREAD

**Issue by sigseg1v** [griever989/endless-expedition#52]
If a web server has uptime longer than the HTTPS certificate, or if it's simply running when a cert needs to be updated, it should automatically load the updated certificate. See https://github.com/nodejs/node/pull/23644
The alternative is restarting after the cert is renewed which also works but isn't ideal.

**Comment by joshxyzhimself** [comment]
Hi, curious about this. Does `server.setSecureContext(options)` work with you?

At https://nodejs.org/api/tls.html#tls_server_setsecurecontext_options it says

> The server.setSecureContext() method replaces the secure context of an existing server. Existing connections to the server are not interrupted.

---

Edit: Lol I thought I'm at https://github.com/nodejs/node repo sorry
